<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <AssemblyName>OSFormulaFleeV5</AssemblyName>
        <AssemblyTitle>OSFormulaFleeV5</AssemblyTitle>
        <Description>Custom implementation of Flee (Fast Lightweight Expression Evaluator) for the Formula OutSystems Forge component.</Description>
        <Copyright>Copyright © 2025 Formula/Flee Contributors</Copyright>
        <Authors>Formula/Flee Contributors</Authors>
        <Company>Formula/Flee</Company>
        <Product>Formula/Flee</Product>
        <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>10.0</LangVersion>
        <Title>Formula/Flee</Title>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Resources\DocComments.xml" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Resources\DocComments.xml" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.ComponentModel" Version="4.3.0" />
        <PackageReference Include="System.Reflection" Version="4.3.0" />
        <PackageReference Include="System.Reflection.Emit" Version="4.7.0" />
        <PackageReference Include="System.Reflection.Emit.ILGeneration" Version="4.7.0" />
        <PackageReference Include="System.Reflection.Emit.Lightweight" Version="4.7.0" />
    </ItemGroup>

</Project>
